# Generated by Django 4.1.2 on 2024-01-31 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0031_appointment_either_provide_quote_or_service_not_both"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleInviatation",
            fields=[
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="email address"),
                ),
                (
                    "invitation_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("is_expired", models.BooleanField(default=False)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
